### ISSUE TITLE
Something seems wrong in the Ingredients list

### ISSUE THREAD

**Issue by blairg23** [PunishXIV/Artisan#110]
I just noticed the Ingredients list counter seems to be wrong (see attached screenshot)? For instance the required vs. remaining needed numbers don't seem to add up.

![image](https://github.com/user-attachments/assets/1c50aa70-2082-4f62-9dac-4deafd9f5a1e)

**Comment by Taurenkey** [comment]
The remaining column updates depending on what you have in your inventory/retainers for not just the current item but items related to it. Looking at the top line, you need 2 less whetstones because I can see you have 2 black stars already. Without seeing the unfiltered list I can’t point any more things like this out but that’s what will be happening.

**Comment by blairg23** [comment]
> The remaining column updates depending on what you have in your inventory/retainers for not just the current item but items related to it. Looking at the top line, you need 2 less whetstones because I can see you have 2 black stars already. Without seeing the unfiltered list I can’t point any more things like this out but that’s what will be happening.

I did follow only the items it said it required and I ended up with a message that said I didn't have enough items to finish one of the crafts so not sure what happened there.

**Comment by blairg23** [comment]
I'm still seeing oddness here. The ingredients for Astral Oil weren't in stock so I just bought some Astral Oil (it said I needed 1 more for a total of 2). When I bought the oil, it shows I have 2 in my inventory but the amount of ingredients to make it still show up (Astral Oil did disappear from the ingredient list, however). I closed the list and re-opened it to refresh it and it still shows up in the list. ![image](https://github.com/user-attachments/assets/b78bed8b-b97a-4819-b28b-230bcecd9f7b)

Side note: I'm having some issues because I made a huge list of items for a small apt housing build and I'm running out of inventory part way through. What's the best way to continue a list when you have to stop / start a lot. The resume feature doesn't always work for me because I need to purchase items part-way through so I have to close the screen to be able to see the ingredients list feature. I know I COULD export as a text document but that feels like I'm defeating the point of the ingredient list automation.

**Comment by blairg23** [comment]
@Taurenkey I think I figured out the Astral oil quandary. The item that gets crafted is 4x the item. So since 2x was required by the recipe, it actually required 8 Astral Oils (in the recipe list, it says Astral Oil x2 (8 total) which confused me greatly. I am still confused why buying ONE Astral Oils took it off the list however. It might be some weirdness with the fact that 4 get created each craft.
