### ISSUE TITLE
Final Appraisal abuse

### ISSUE THREAD

**Issue by Nerrozi** [PunishXIV/Artisan#120]
Perhaps i may have missed an option somewhere or something, but the solver will continue to waste a synthesis action with a final appraisal instead of just switching to work on quality

**Comment by Taurenkey** [comment]
It will be intended as part of the algorithm. The standard solver will push progress until it is 1 unbuffed basic synthesis away from completion to ensure that regardless of what happens with quality, the craft can succeed.

**Comment by Nerrozi** [comment]
So final appraisal is a substitute for the algorithm right now, or is it working as intended?

**Comment by Taurenkey** [comment]
It's not a substitute, it *is* the algorithm. If it's using final appraisal then it means your progress left is more than one unbuffed basic synthesis, but less than your next gain (as in it would complete your craft early).

**Comment by Nerrozi** [comment]
Ohhh, I see what you are saying, my apologies. I did however, just end up making a macro for it to follow, since I'm doing the ishgard restoration crafts, I didn't want it to chase a quality I didn't need it to reach.
