### ISSUE TITLE
Feature Request: Show all needed materials in Ingredients list.

### ISSUE THREAD

**Issue by pigsflew** [PunishXIV/Artisan#122]
If I want to craft, say, a Calfskin Rider's Jacket, I add it with all subcrafts, then flip to the ingredients list to figure out what I need to go fetch to make the whole list.

The ingredients list then shows me this:

![Artisan Crafitng List - Ingredients](https://github.com/user-attachments/assets/4bd23554-c06c-4e8a-a137-1c7005cdf81b)

As of right now, Artisan seems to *only* list gatherables, and not even all of those. I need craft Dwarven Mythril Ingots, which require Mythrite ore *and* Dimythrite; as well as Megalania Leather, requiring Megalania skin and Ashen Alumen, the latter of which is *also* missing. Finally, I need Calf Leather, which must be purchased on the market board to assemble the final product.

Why aren't these other items listed?

I like the compact display of Artisan crafter, and cannot do without the rest of the artisan toolkit, but I wish it had a crafting planner more like Allagan Tools, *or* have Artisan simply integrate with / link through to Allagan Tools for this functionality.

![Allagan Tools - Crafts List](https://github.com/user-attachments/assets/a000d209-3174-4b94-a8af-3c6113f0829e)

**Comment by pigsflew** [comment]
It'd actually be really cool if, on the AllaganTools side, there could be a "Craft with Artisan" that would simply create an Artisan crafts list of any missing precrafts and outputs, sort it, and execute.

Then I'd just turn off the Artisan Context Menu Options and not look at Artisan lists except in that direction.

**Comment by Taurenkey** [comment]
1. Artisan shows ingredients required for items on your list, if something is missing then check your filters and if a header is in red, right click it to reset it.

2. There can't be any integration in Allagan Tools, it's an official Dalamud plugin and Artisan doesn't meet the requirements to be an official Dalamud plugin (it's automation, not allowed). That, and it's not my plugin, so I don't have a say in what goes into it.
