### ISSUE TITLE
Don't upgrade Basic or Standard Touch when it's part of a combo

### ISSUE THREAD

**Issue by kapsi1** [PunishXIV/Artisan#125]
If "upgrade actions" for a macro is turned on, and it upgrades Basic Touch or Standard Touch to Precise Touch on Good condition, the following Standard/Advanced touch won't be in combo state, and won't have its CP cost lowered. This breaks macros.

**Comment by Taurenkey** [comment]
That is why there's the option for "Combo Action" as part of the macro, so you *can* do this.

**Comment by kapsi1** [comment]
Thanks
