### ISSUE TITLE
"Max Quality%" attribute does not have an effect when creating collectibles

### ISSUE THREAD

**Issue by sheiun** [PunishXIV/Artisan#23]
Due to insufficient equipment grade or attributes, it may only be possible to reach the first or second stage when creating collectibles. I would like to modify or add a field to limit the quality progression bar.

**Comment by haysidney** [comment]
I've noticed this too. It works if you set it to 0, but anything else seems to just defer to 100% quality.

**Comment by kawaii** [comment]
The quality slider has no effect on collectibles by intentional design. It's not possible for the automatic solver to be that precise.
