### ISSUE TITLE
Feature: Required consumables for macros

### ISSUE THREAD

**Issue by KorFeN** [PunishXIV/Artisan#24]
It is currently only for Crafting Lists or Endurance mode right now. But it would make more sense to have it for your macros instead, or both.

Current workflow right now if I wanna wake alot of one item that requires a tincture and food. Then I either have to go into settings, and enable, required consumables(and remember to turn it off), or I have to make a crafting list with that item and add it as many times I intend to craft it and there I can add required food/tincture.

But when you make macros you always have a certain consumable combination in mind. So it makes sense to have it there instead. Then I could just open the Crafting menu and click the Endurance mode button and it starts crafting, and the Macro makes sure I have the required consumables.

**Comment by Taurenkey** [comment]
No, macros are for crafting execution only.

**Comment by KorFeN** [comment]
Yes, but either this or something similar to attach Food requirements to Macros would greatly simplify crafting. 

I don't think having to go into the settings menu to enable food / tincture refreshing is a good solution. This often ends up either wasting food on crafts that dont need food, or starting a craft which needed food, but you didn't have it popped, so you end up wasting materials.

I am not saying that macros is the only way, but it would be the easiest way to implement this.
