### ISSUE TITLE
Macro does not advance when executing upgraded actions

### ISSUE THREAD

**Issue by syldrathecat** [PunishXIV/Artisan#26]
Because of the change made in 918006f0025b5872fecff61d4936a2bc57c6d8b1 -- specifically https://github.com/PunishXIV/Artisan/blob/918006f0025b5872fecff61d4936a2bc57c6d8b1/Artisan/RawInformation/ActionWatching.cs#L119 where it checks if the executed action was programmed in to the macro, using the "Upgrade Quality Actions" to substitute macro actions causes the macro not to advance and it will execute extra actions instead.

**Comment by Taurenkey** [comment]
This has been fixed on the testing build, as per this branch.

https://github.com/PunishXIV/Artisan/commit/918006f0025b5872fecff61d4936a2bc57c6d8b1#diff-9ccc6a5730b63a9cc509eeebed4f27832dea15d04bdaf6505657468fe7ed5902
