### ISSUE TITLE
Feature: remember amount of HQ/NQ material used, or disable auto HQ mat selection

### ISSUE THREAD

**Issue by requiem2017** [PunishXIV/Artisan#28]
For example, a recipe necessitates two ingredients, but my macro only requires one HQ ingredient to craft the recipe in HQ quality. However, the current endurance mode automatically utilizes the maximum amount of HQ material, which is 2.

Could you kindly add a checkbox to disable the auto HQ material quantity adjustment, or implement a mechanism to remember the amount of HQ/NQ material used, or introduce an option for "Minimum starting quality" in the macro settings? This would significantly save time when crafting the HQ ingredient.

**Comment by AcidAshe** [comment]
This would be amazing. Currently, this is one of the 2 things holding me back from swapping over to Artisan from SND completely. If this were added in tandem with the ability to also pull the necessary amount of HQ ingredients from retainers, it would be a smooth transition for those using SND to do master crafts.
