### ISSUE TITLE
Unable to use endurance mode for the WVR lv.88 recipe "AR-Caean Velvet"

### ISSUE THREAD

**Issue by Lightzy** [PunishXIV/Artisan#29]
I've found I'm unable to use endurance mode for this recipe specifically. No other recipes are affected. I first noticed this issue a few weeks back but have rediscovered it recently, so it's not fixed by restarts.

It doesn't seem to matter whether the recipe is found through the crafting log list by level, through favourites, or through search. The window to select a macro shows the previously selected recipe (eg: if I do some Scarlet Moko Cloth first, when I select the AR-Caean Velvet recipe the window incorrectly says "Use a macro for this recipe (Scarlet Moko Cloth)". If the previously selected recipe does not have the required materials to craft (eg: I have no Scarlet Moko Grass), attempting to enable endurance mode on AR-Caean Velvet or use the "Craft X Times" option, Artisan will enable and then disable endurance mode immediately as if it has run out of materials, making no crafts.

I've managed to find a workaround for it by finding a recipe I _do_ have the materials for to select before swapping to AR-Caean Velvet (in this case the AR-Caean Velvet Cap of Fending right below it). The macro selection window is still showing the incorrect recipe (the Cap of Fending) but crafts the AR-Caean Velvet I selected second.

**Comment by Taurenkey** [comment]
This is fixed on our testing version.
