### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by alekiser** [PunishXIV/Artisan#31]
When interacting with the overlay, the game sometimes crashes.

Unhandled native exception occurred at ffxiv_dx11.exe+92F058
Code: C0000005

**Comment by Taurenkey** [comment]
Not enough information

**Comment by alekiser** [comment]
Here are the logs, let me know if you need anything else.
[dalamud_appcrash.txt](https://github.com/PunishXIV/Artisan/files/12546086/dalamud_appcrash.txt)
