### ISSUE TITLE
Auto-deselects materials after Materia extraction in an endurance craft

### ISSUE THREAD

**Issue by daniehjyoo** [PunishXIV/Artisan#32]
I'm quite sure before during an endurance craft it would extract materia from spiritbond gear and continue (with the default max HQ item selection).
However, it now deselects your material selections and disables endurance because of "too many errors in succession."

EDIT: After trying it more, it's only when the craft needs to use a HQ item, it'll be deselected once it goes back to the crafting menu.

**Comment by Taurenkey** [comment]
Not a bug or issue.

![image](https://github.com/PunishXIV/Artisan/assets/30053704/fd94430e-27ab-4896-b597-ce8a945f05fe)
