### ISSUE TITLE
Have to select an item from your inventory error

### ISSUE THREAD

**Issue by FunkeyMonkey** [PunishXIV/Artisan#33]
Loving the plugin so far! Ran into one small issue and not sure if it's a bug or i'm missing a setting somewhere. I created a list with sub items to do my GC stuff and while it was running through the list one of the components it made ended up not being HQ and was NQ. When it got to the recipe to create the item it just spammed **Unable to craft. You have not selected all of the material** I had to pause, select the one HQ item and one NQ item and then hit syn and resume to get it to continue.

Is there an option somewhere to allow using both types that i'm missing? I realize that my settings of Max Quality are what caused this little issue, I have it set to 90% and not 100% as I was doing one of the Ixal faction quests and it kept failing to craft one of the quest items trying to push for 100% HQ. Thoughts? Thanks!

**Comment by Taurenkey** [comment]
I am unable to replicate this behaviour. Perhaps if you could provide more information about the list and the items you were crafting it may shine a light on the issue?

**Comment by AcidAshe** [comment]
Oh, this happened to me yesterday, but with a Gilded Rosewood Fishing Rod. The behavior actually seems to appear with a craft that has to select another item as a material?

**Comment by Taurenkey** [comment]
Ahh yes, the "Have to select an item from your inventory" problem. I do know about it being an issue, but given it stopped being a thing after a while I haven't gotten round to addressing it.

**Comment by FunkeyMonkey** [comment]
Yep, just went through and tried the recipe again, this time making sure i had all HQ mats and it errors on the selecting the bronze barbut helm to use in the craft.

**Comment by zesty-mordant** [comment]
This is happening to me as well but only when the addon stops to do something like repair, use food/potion. When it goes back to start crafting again, the HQ mat is no longer selected and causes it to error out.

**Comment by Justalurker1213** [comment]
This is happening to me as well but only when the addon stops to do something like repair, use food/potion. When it goes back to start crafting again, the HQ mat is no longer selected and causes it to error out.

**Comment by GiacomoLaw** [comment]
Hiya, I am still having this problem? Thanks
