### ISSUE TITLE
Opening Artisan greys screen, unable to click

### ISSUE THREAD

**Issue by peterberbec** [PunishXIV/Artisan#36]
If I open the main Artisan Window, my entire screen goes slightly grey and my mouse is unable to click on anything in the UI.

This occurs both in-game or at the main window. Both with the `/artisan` command, or opening through Dalamud trigger the error. Windowed, borderless windowed and full-screen game mode are equally effected. The resolution I play at does not change this behavior.

I am able to quit the game using keyboard shortcuts, but am unable to quit Artisan. Logging out does not fix the issue, only a full quit of the game does.

I have disabled all other plugins, and restarted the game. The issue still occurs.

Only the main Artisan settings window causes this effect. The side-window on the crafting log appears fine and crafts function correctly.

I am using Artisan v2.1.0.10 and Dalamud D9.0.0.2

Normal UI
![artisan_bug_ingame_normal](https://github.com/PunishXIV/Artisan/assets/17226353/cd0742d6-8837-4c8b-8a33-55985f229693)

Normal UI, Artisan Opened
![artisan_bug_ingame_gray](https://github.com/PunishXIV/Artisan/assets/17226353/d06fd81c-9d77-45e1-a9e8-e60a5d0ab0dd)

Main Menu
![artisan_bug_menu](https://github.com/PunishXIV/Artisan/assets/17226353/940136ab-d4c2-4729-9303-24c4c2d8b627)

Main Menu, Artisan Opened
![artisan_bug_menu_gray](https://github.com/PunishXIV/Artisan/assets/17226353/e20d44fd-d69b-4c3b-9d18-7c2901b44a71)

**Comment by Taurenkey** [comment]
Do you use multiple monitors? What is happening is a popup explaining a recent change, once closed won't reappear. It's possible the popup has appeared on another screen for some reason.

**Comment by peterberbec** [comment]
I do use multiple monitors.

If I unplug all but one of my monitors and switch to fullscreen mode, I would be able to see the dialog box?

**Comment by peterberbec** [comment]
That did it!

![image](https://github.com/PunishXIV/Artisan/assets/17226353/d23a6ecb-14f6-4645-90e4-e32749d7f133)

I'm not sure if their is anything to do to resolve this any other way. Artisan tries to put the dialog box somewhere sane, but my multiple monitors must have broken that logic.

I'm going to close the issue.
