### ISSUE TITLE
Feature Request: Export remaining ingredients list as plain text

### ISSUE THREAD

**Issue by Uriei** [PunishXIV/Artisan#52]
Hi,

could we have a button to export remaining/needed ingredients to fulfill the current crafting list ingredient list as plain text like
```
10x Iron Ore
20x Upland Wheat
```
it would also work for tools with parsers like in ARC allow to just click import to import the whole missing ingredient list instead of adding them one by one

**Comment by adambennett55** [comment]
Would it be possible to add on to this to export the list with other data as well, like the other headers, maybe this could be an option and maybe which header from the ingredient list we want exported with can be an option as well, maybe as a CSV or Json (also could be option)

could this all be done from the command line as well,

ex
/artisan exportingredients -remainingonly -headers required,source,gatheredzone

also would it be possible to somehow make a List<string> that could be read from other plugins vs exporting to the clipboard? or a string formatted as json? (maybe also an option -ipclist or -ipcjson)
