### ISSUE TITLE
Auto Action Mode not continuing after first action.

### ISSUE THREAD

**Issue by Gwiberr** [PunishXIV/Artisan#55]
Just something I have experienced recently; whenever I am mass crafting, Auto Action Mode does the first action of a macro and then stops. I have to manually toggle AAM off and then back on to get it to continue the macro for the craft.

However if I leave it to use recommended actions or the new Expert Recipe Solver mode, it will work as intended. Just macros are bugging out AAM for me.

**Comment by Taurenkey** [comment]
If your macro is using a specialist action, you will need to enable "Use Specialist Actions" under the standard solver settings. It's a bug I'm aware of and will be fixed shortly.

**Comment by Gwiberr** [comment]
Appreciate the speedy response and everything you do <3
