### ISSUE TITLE
Feature request: allow locking position of the crafting log's side window

### ISSUE THREAD

**Issue by PrincessRTFM** [PunishXIV/Artisan#60]
I usually have my crafting log window in the upper right of my screen, which means that [this window](https://github.com/PunishXIV/Artisan/assets/8753564/8d7e91f8-a126-4c9a-ae5d-9f8ebf5a0638) is hidden off-screen. I'd like to keep my log there, but still have that window in a fixed position, which is currently only possible when it's attached to the right side of the crafting log.

Ideally, it would be nice to be able to attach to it to the right side as well, but the most useful thing for me would be a way to simply lock its position, so that I can put it somewhere and be sure it'll stay right there.

**Comment by Taurenkey** [comment]
Hi, the option to lock it is already in the plugin, under UI settings.

**Comment by Taurenkey** [comment]
Ok, I see what you're looking for now. I can add this as an option if the window is unattached from the recipe window for sure.

**Comment by PrincessRTFM** [comment]
Much appreciated!

**Comment by Taurenkey** [comment]
This is now in the plugin.
