### ISSUE TITLE
Standard Solver logic gridlock

### ISSUE THREAD

**Issue by offyerrocker** [PunishXIV/Artisan#61]
Under certain circumstances during a craft, the Standard Solver will stall and fail to perform the recommended action or any actions at all, causing the character to indefinitely idle at the craft until player intervention.

I've observed this happening only when all of the following circumstances are met:
* The "condition" of the craft is "Good" or "Excellent"
* The "durability" state of the craft is low (only observed at 10 durability but presumably any value under the threshold would suffice)
* The character's crafter level is less than 13 (ie. the action "Tricks of the Trade" is not available)

(I'd speculate that this is due to a missing availability check for `TricksOfTrade` somewhere, maybe in `Solve()`, but I should note I haven't tried applying any fixes myself yet.)

Edit: The expected behavior in these circumstances would be to use "Master's Mend" or some progress-increasing ability to complete the craft, under the assumption that these would be preferable to failing the craft

**Comment by Taurenkey** [comment]
Yes, there's a bit of a logic error with the contingency Tricks, will be fixed in next update
