### ISSUE TITLE
Add an option to "Add to New Crafting List" in the crafting log

### ISSUE THREAD

**Issue by KestrelWild** [PunishXIV/Artisan#63]
Right now you can "Add to Current Crafting List" or "Add to Current Crafting List (with Sub-crafts)" from the crafting log. What I really seem to need most is the ability to add an item to a NEW crafting list. 

Thanks for reading!

**Comment by Taurenkey** [comment]
This is already a feature. If you do not have a list selected in the UI, it will default to making a new list, otherwise it will add it to the list you already have selected.
