### ISSUE TITLE
Unable to use Withdraw From Retainer in List and from crafting Log after 6.58 patch

### ISSUE THREAD

**Issue by mitch2012mitch** [PunishXIV/Artisan#64]
After attempting to use the Re-stock from retainers option in a crafting list, being next to a summoning bell will select and open the retainers interface but will not proceed from there. Selecting Withdraw from Retainer in the crafting menu does not seem to get any response next to a summoning bell and does not select it.

**Comment by Taurenkey** [comment]
This should be fixed now
