### ISSUE TITLE
Load error after updating to v3.0.5.0

### ISSUE THREAD

**Issue by CharloZhu** [PunishXIV/Artisan#65]
Hi, I got this error after updating to the latest version. The patch of my game is CN 6.50. 
![image](https://github.com/PunishXIV/Artisan/assets/43008381/91aa03c1-de9b-4071-9a44-4513f6b455c7)

**Comment by 59906** [comment]
me too

**Comment by CharloZhu** [comment]
已收到邮件！-Charlo

**Comment by 59906** [comment]
![f741ddc932ddad34bd4dff8f3c83dec8](https://github.com/PunishXIV/Artisan/assets/141056198/48eee0f4-02cd-4c91-96d8-05234f30bf0e)

**Comment by EFHT** [comment]
same here.

**Comment by lixiyuan223** [comment]
3.0.5.1 too

**Comment by Taurenkey** [comment]
Artisan is now running on .NET 8. If this is CN, I do not know if they have updated Dalamud to .NET 8 like global has. If they have not, **Artisan will not load until they update their Dalamud to .NET 8.**

**Comment by lixiyuan223** [comment]
https://puni.sh/api/plugins/download/6/Artisan/versions/testing.zip




a
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PunishXIV/Artisan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月21日(星期四) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PunishXIV/Artisan] Load error after updating to v3.0.5.0 (Issue #65)





 
Artisan is now running on .NET 8. If this is CN, I do not know if they have updated Dalamud to .NET 8 like global has. If they have not, Artisan will not load until they update their Dalamud to .NET 8.

**Comment by lixiyuan223** [comment]
https://puni.sh/api/plugins/download/6/Artisan/versions/testing.zip


The test version can be used.
&nbsp;


a
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PunishXIV/Artisan] Load error after updating to v3.0.5.0 (Issue #65)





 
Artisan is now running on .NET 8. If this is CN, I do not know if they have updated Dalamud to .NET 8 like global has. If they have not, Artisan will not load until they update their Dalamud to .NET 8.

**Comment by lixiyuan223** [comment]
CN6.5  The test version can be used.

https://puni.sh/api/plugins/download/6/Artisan/versions/testing.zip

**Comment by SchAHS** [comment]
> CN6.5 The test version can be used.
> 
> https://puni.sh/api/plugins/download/6/Artisan/versions/testing.zip

Excuse me but how to install it?

**Comment by Taurenkey** [comment]
Closing as this will be resolved with a CN Dalamud update and is not Artisan specific.

**Comment by 59906** [comment]
Can we find the old one in any web,work with CN Dalamud

**Comment by Yanheixi** [comment]
they might fix the problem, but it still can't work .   
![Uploading problem.png…]()
