### ISSUE TITLE
Artisan unable to perform automatic repair.

### ISSUE THREAD

**Issue by yunarii** [PunishXIV/Artisan#66]
This might be known already but just in case...

Since the update today, using 3.0.5.0, Artisan will stop to repair damaged gear at the threshold set but doesn't actually repair the gear. There is sufficient dark matter on hand, no df queue, etc. The repair menu remains open, and will re-open automatically, until you manually click repair. After repairing Artisan will resume crafting.

Here's what's captured in the log under verbose.

18:59:42.982 | VRB | [HM] Detected hook trampoline at 7FF6706FC9C0, stopping jump resolution.
18:59:42.982 | VRB | [HM] Registering hook at 0x7FF6706FC9C0 (minBytes=0x0, maxBytes=0x32)

Thanks for your time and help! I'm new to using Artisan, just within the past few weeks, but it's a blessing :)

**Comment by Taurenkey** [comment]
This should be fixed now
