### ISSUE TITLE
adjusting quantity in a list doesnt adjust subcraft

### ISSUE THREAD

**Issue by leroidubid** [PunishXIV/Artisan#71]
I was hoping that adjusting the quantity in a craft would adjust the subcraft but it does not.
Bug or expected ?
If expected, it would be a nice feature to have
![image](https://github.com/PunishXIV/Artisan/assets/4203121/837074a9-bc6c-4d63-b561-a65a17b6ec90)

**Comment by Taurenkey** [comment]
It's expected behaviour. If you want to adjust them all at the same time, you add the recipe from the dropdown list again.
