### ISSUE TITLE
[FEATURE REQUEST] Being able to add multiple quantity of a recipe to crafting list

### ISSUE THREAD

**Issue by leroidubid** [PunishXIV/Artisan#72]
Would be cool with maybe a modifyer (like ALT, SHIFT, CTRL) to right click > add to crafting list, that would open a popup where you can enter a number that would be the quantity to add to the crafting list (adjusting th subcraft quantity too)
![image](https://github.com/PunishXIV/Artisan/assets/4203121/7766019b-56b7-4bc6-91dd-693447be73b7)

**Comment by Taurenkey** [comment]
You can already adjust the value in the settings.

**Comment by leroidubid** [comment]
> You can already adjust the value in the settings.

Yes I know but when dealing with big lists, finding the top recipes and adjusting one by one every recipes + every subcraft is not the same as just having to specify the number at the beginning
