### ISSUE TITLE
I clicked ‘’Craft‘ ’but it didn't work 

### ISSUE THREAD

**Issue by Yanheixi** [PunishXIV/Artisan#74]
When crafting items, the materials are complete, the equipment is normal, and the crafting mode is adopted. However, pressing the crafting button will not allow you to craft it, and you will not be able to craft it in-game. You must close the plugin to make it.The number of crafts is also set, but it still can't be moved.
Is there a problem with my settings?
![1](https://github.com/PunishXIV/Artisan/assets/164340506/05e101a9-51e9-4cca-90bb-bb38dceef38a)
![2](https://github.com/PunishXIV/Artisan/assets/164340506/2dc36a74-aad3-4b52-9878-73c62510010c)

**Comment by Taurenkey** [comment]
Please view this post on our Discord server https://discord.com/channels/1001823907193552978/1003395035762528387/1253322501010751510

It is an issue specific to CN just now.

**Comment by hebo1982** [comment]
@Yanheixi @Taurenkey 

I got this error too. how to fix?
