### ISSUE TITLE
Solver not using new crafting abilities.

### ISSUE THREAD

**Issue by Petra105** [PunishXIV/Artisan#76]
The solver isn't using the new crafting abilties of
Immaculate Mend - Restores all item durability for 112cp
Trained Perfection - Reduces durability loss of next action to 0. Once per synthesis for 0cp
Refined Touch - Increases quality 100% efficiency 100% success. combo action basic touch. Increases Inner Quiet stack by one for 24cp
I don't know if these are or are not programmed in but here they are if they are not.

**Comment by Taurenkey** [comment]
I haven't put them into the solvers yet because it's still early and I want to see where people go with their usages. They will come in time.
