### ISSUE TITLE
Can't enable Endurance mode

### ISSUE THREAD

**Issue by xKiisa** [PunishXIV/Artisan#78]
I cannot seem to enable Endurance mode anymore. It tells me i am missing the required materials, even though i have them. I tried different recipes and it happens with all of them

![23-52-12](https://github.com/PunishXIV/Artisan/assets/104528108/25afa1a5-30c5-4d3b-ab2f-7dea26bfed99)

**Comment by Taurenkey** [comment]
Given you're also missing the consumable/solver assignment part of the window, it looks like there's something wrong with your game in general. Can you check `/xllog` for errors from other plugins, and try repairing your Dalamud installation.

**Comment by K242626** [comment]
I'm having a similar issue, except endurance mode is available for some crafts but not others despite having the requisite materials. 
![image](https://github.com/PunishXIV/Artisan/assets/84142035/909e4880-8f2b-46e6-baa3-c8deeaf828fe)
![image](https://github.com/PunishXIV/Artisan/assets/84142035/a0bc003e-1a3f-4cd9-8fa7-6cda9176c489)

**Comment by Taurenkey** [comment]
> I'm having a similar issue, except endurance mode is available for some crafts but not others despite having the requisite materials. ![image](https://private-user-images.githubusercontent.com/84142035/347245481-909e4880-8f2b-46e6-baa3-c8deeaf828fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODg0MTcsIm5iZiI6MTcyMDU4ODExNywicGF0aCI6Ii84NDE0MjAzNS8zNDcyNDU0ODEtOTA5ZTQ4ODAtOGYyYi00NmU2LWJhYTMtYzhkZWVhZjgyOGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA1MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NjhlMTU1NzhiZDA5Y2EyNzYyZjlkYTBjMGJkNzE0MTAzNDQ5NWMyZjcwZGIzMGYzOGQ5NDgwYTRlNDNkYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3esVsVnsZY11uADLl8mKIf3qxVNNw7hthyflVWjOgg) ![image](https://private-user-images.githubusercontent.com/84142035/347245500-a0bc003e-1a3f-4cd9-8fa7-6cda9176c489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODg0MTcsIm5iZiI6MTcyMDU4ODExNywicGF0aCI6Ii84NDE0MjAzNS8zNDcyNDU1MDAtYTBiYzAwM2UtMWEzZi00Y2Q5LThmYTctNmNkYTkxNzZjNDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA1MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMmE5ZTVkN2M2YmUwYTU2MTkwN2MwMGI4MmMxMDdmNTJhODFjM2FhNGEzZWVjNjJhYTc4ODgxZTgxNmYzNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WON7p_XBpCTlBHpZBkK86FF859DDYkTAoFh9b9QdxvY)

You’re missing crystals.
