### ISSUE TITLE
[Feature Request]: More convenient access to Craft Lists.

### ISSUE THREAD

**Issue by maxrmax** [PunishXIV/Artisan#79]
First: Thank you for creating this plugin. It is great!

My request is hopefully a simple one.
![image](https://github.com/PunishXIV/Artisan/assets/113170244/604c3862-9e13-433b-931f-75a891341c21)

It would be great if you could add multiple recipes to a quick craft list for x amounts or handle the current recipe like a craft list until x amounts are crafted (endurance possible).
Something like this:
Rightclick > add recipe to queue for X amount. > Start crafting. >finished > empty list/queue. (or manually empty it)
Possibly with any amount of recipes!
Right now you have to add it, then edit the amounts you want and then start crafting it from the menu.

**Comment by Taurenkey** [comment]
The intended way of making lists is not through context menus, that's just for making a quick addition to a list and isn't meant to serve as the main way doing it.

The main way is through the list editor window itself, where you'll add the recipes through the dropdown and you can adjust values there a lot easier.
