### ISSUE TITLE
Endurance mode consumable selector and Craft X times no longer display in v4.0.0.10

### ISSUE THREAD

**Issue by mczub** [PunishXIV/Artisan#90]
The selector to pick which food, tincture, manual, etc. along with the Craft X times selector no longer display after updating to ver v4.0.0.10

![image](https://github.com/user-attachments/assets/68c8eee8-0568-4799-b8b3-6bfe37a7f864)
![image](https://github.com/user-attachments/assets/dbcd16fa-f8d4-44bb-beea-139aafb4198f)

**Comment by klotterc** [comment]
were you able to resolve this? i have the same issue

**Comment by mczub** [comment]
fixed this by changing my dalamud branch from stg to release (using /xlbranch)
