### ISSUE TITLE
Synthesis fails on easy crafts because of incorrect progress estimation

### ISSUE THREAD

**Issue by Sundava** [PunishXIV/Artisan#94]
On some easy crafts, completable with Trained Eye, the Standard Solvers fails the synthesis completely, going to 0 durability without reaching 100% progress, even with enough CP to spare for restore durability.

See the solver simulator here:
![image](https://github.com/user-attachments/assets/9cf36196-f16c-4854-9aec-b1bd4c6bfa4b)

This is with a full i690 crafted gear.
Any progress action other than the basic synthesis here would have completed the craft, I'm not really sure why he is so intent on using Basic Synthesis for the last step.

The solver manages to finish the craft only with a good/excellent proc, where it can use a Delicate Synthesis to reach 100% progress.

**Comment by Taurenkey** [comment]
This should now be resolved.
